exports.NAVBAR_LOGIN_START = 'NAVBAR_LOGIN_START'

exports.NAVBAR_LOGIN_END = 'NAVBAR_LOGIN_END'

exports.NAVBAR_REGISTER_START = 'NAVBAR_REGISTER_START'

exports.NAVBAR_REGISTER_END = 'NAVBAR_REGISTER_END'
